name: contact_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.0.2

  # Dependency Injection
  get_it: ^7.2.0

  # Internationalization and localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  # Functional programming 
  dartz: ^0.10.0

  # Data Class
  equatable: ^2.0.3

  # Loading Animation
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0

  # Routing
  get: ^4.3.8

  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
